<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Database\Eloquent\Relations\HasMany;
use Illuminate\Support\Str;

/**
 * Article Model
 * 
 * Represents both original and rewritten articles.
 * Original articles are scraped from BeyondChats.
 * Rewritten articles are generated by the AI Rewriter service.
 */
class Article extends Model
{
    use HasFactory;

    protected $fillable = [
        'title',
        'slug',
        'content',
        'source_url',
        'version',
        'is_rewritten',
        'parent_article_id',
        'references',
        'published_at',
    ];

    protected $casts = [
        'references' => 'array', // Automatically cast JSON to array
        'published_at' => 'datetime',
        'is_rewritten' => 'boolean',
    ];

    /**
     * Boot method to auto-generate slug from title
     */
    protected static function boot()
    {
        parent::boot();

        static::creating(function ($article) {
            if (empty($article->slug)) {
                $article->slug = Str::slug($article->title);
            }
        });
    }

    /**
     * Get the parent article (for rewritten articles)
     */
    public function parent(): BelongsTo
    {
        return $this->belongsTo(Article::class, 'parent_article_id');
    }

    /**
     * Get rewritten versions of this article
     */
    public function rewrittenVersions(): HasMany
    {
        return $this->hasMany(Article::class, 'parent_article_id');
    }

    /**
     * Scope to get only original articles
     */
    public function scopeOriginal($query)
    {
        return $query->where('version', 'original');
    }

    /**
     * Scope to get only rewritten articles
     */
    public function scopeRewritten($query)
    {
        return $query->where('version', 'rewritten');
    }

    /**
     * Scope to get only unrewritten original articles
     * (Articles that haven't been processed by AI Rewriter yet)
     */
    public function scopeUnrewritten($query)
    {
        return $query->where('version', 'original')
                     ->where('is_rewritten', false);
    }

    /**
     * Scope to get latest article
     */
    public function scopeLatest($query)
    {
        return $query->orderBy('published_at', 'desc')
                     ->orderBy('created_at', 'desc');
    }
}
